#!/bin/bash

echo "=========================================="
echo "Déploiement Glowing Cosmetics - Hostinger"
echo "=========================================="
echo ""

# Exécuter ces commandes sur le serveur Hostinger
echo "Copiez et exécutez ces commandes sur le serveur SSH:"
echo ""
echo "# 1. Créer le dossier laravel et cloner le repository"
echo "mkdir -p ~/laravel"
echo "cd ~"
echo "git clone https://github.com/simonet85/cosmetics-app.git laravel"
echo ""
echo "# 2. Installer les dépendances Composer"
echo "cd ~/laravel"
echo "composer install --optimize-autoloader --no-dev"
echo ""
echo "# 3. Configurer les permissions"
echo "chmod -R 755 ~/laravel"
echo "chmod -R 775 ~/laravel/storage"
echo "chmod -R 775 ~/laravel/bootstrap/cache"
echo ""
echo "# 4. Copier et configurer le fichier .env"
echo "cp .env.example .env"
echo "nano .env  # Éditer avec les bonnes valeurs"
echo ""
echo "# 5. Générer la clé d'application"
echo "php artisan key:generate"
echo ""
echo "# 6. Configurer le dossier public_html"
echo "cd ~/public_html"
echo "rm -rf *"
echo "rm -rf .[!.]*"
echo ""
echo "# 7. Créer le fichier index.php personnalisé"
echo "cat > ~/public_html/index.php << 'EOFINDEX'"
echo "<?php"
echo ""
echo "use Illuminate\Contracts\Http\Kernel;"
echo "use Illuminate\Http\Request;"
echo ""
echo "define('LARAVEL_START', microtime(true));"
echo ""
echo "require __DIR__.'/../laravel/vendor/autoload.php';"
echo ""
echo "\$app = require_once __DIR__.'/../laravel/bootstrap/app.php';"
echo ""
echo "\$kernel = \$app->make(Kernel::class);"
echo ""
echo "\$response = \$kernel->handle("
echo "    \$request = Request::capture()"
echo ")->send();"
echo ""
echo "\$kernel->terminate(\$request, \$response);"
echo "EOFINDEX"
echo ""
echo "# 8. Copier le .htaccess"
echo "cp ~/laravel/public/.htaccess ~/public_html/.htaccess"
echo ""
echo "# 9. Créer des liens symboliques pour les assets"
echo "ln -s ~/laravel/public/build ~/public_html/build"
echo "ln -s ~/laravel/public/images ~/public_html/images"
echo "ln -s ~/laravel/public/vendors ~/public_html/vendors"
echo "ln -s ~/laravel/public/css ~/public_html/css"
echo "ln -s ~/laravel/public/js ~/public_html/js"
echo ""
echo "# 10. Créer le lien symbolique pour storage (alternative à php artisan storage:link)"
echo "# Comme exec() est désactivé, on crée le lien manuellement"
echo "ln -s ~/laravel/storage/app/public ~/public_html/storage"
echo ""
echo "# 11. Exécuter les migrations"
echo "cd ~/laravel"
echo "php artisan migrate --force"
echo ""
echo "# 12. Optimiser Laravel"
echo "php artisan config:cache"
echo "php artisan route:cache"
echo "php artisan view:cache"
echo "composer dump-autoload -o"
echo ""
echo "=========================================="
echo "Déploiement terminé!"
echo "=========================================="
